### ISSUE TITLE
Heatmap.js not working with Firefox 30 anymore

### ISSUE THREAD

**Issue by dh1tw** [pa7/heatmap.js#108]
Hi, 
Heatmap.js stopped working with the latest upgrade of Firefox (currently version 30.0), OS Windows, it still works in FF under OSX. 

It's easy to reproduce - just go to the project's site (http://www.patrick-wied.at/static/heatmapjs/#) and press "Activate Website Heatmap". Nothing will happen.

Unfortunately, JS console doesn't throw an error. Anyone with an insight into the fine heatmap.js code has an idea what could be the problem?

**Comment by nirajmah4023** [comment]
Still facing same issue withFF and heatmap.js
