### ISSUE TITLE
bug in leaflet-heatmap if layer is not enabled by default

### ISSUE THREAD

**Issue by dgorissen** [pa7/heatmap.js#130]
Say you do not add the heatmap layer to the list of layers on map creation but rather as an optional overlay that is not shown by default.

If you then select the layer in the selection control, onAdd() never gets called which means _heatmap is not initialized and the code fails on line 125 in _update:

`this._heatmap.setData(generatedData);`

The workaround is to add the layer to the layers list on map creation, but then immediately remove it again. Then showing/hiding the layer with the layers control works as expected.

Working off develop branch

**Comment by pa7** [comment]
Fixed and will be part of the next tagged version :)
