### ISSUE TITLE
Heatmap.js error in example

### ISSUE THREAD

**Issue by styopdev** [pa7/heatmap.js#132]
m try to use heatmap.js library, in example code, browser console get error Uncaught TypeError: Cannot read property 'style' of null on line 362 I didn't touch to example code, but its not working
Thanks for help.
Full Question here
http://stackoverflow.com/questions/25523411/heatmap-js-error-in-example

**Comment by IvoPereira** [comment]
I'm having this problem too. Does v2 fix this? Isn't it on Bower?

**Comment by bgp92** [comment]
Hi there! So this problem is fixed when you use v2. Since I used bower to fetch heatmap it downloaded v1. Please update the bower.
@IvoPereira You should use v2 of it, that will do.

**Comment by ruman2693** [comment]
Guys I am getting error "Unable to get property 'create' of undefined or null reference" on  this._heatmap = h337.create(this.cfg); in leaflet-heatmap.js file can anybody help????
