### ISSUE TITLE
Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.

### ISSUE THREAD

**Issue by andrewboni** [pa7/heatmap.js#142]
```
Uncaught IndexSizeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source width is 0.
```

Has anyone seen this error before? Only happens some of the time- not 100% sure why. I'm generating a heatmap with anywhere from 20 - 100 data points. Thanks!

**Comment by andrewmunsell** [comment]
Also getting the same issue.

**Comment by newelement** [comment]
+1

**Comment by andrewboni** [comment]
FWIW, I was able to get around this issue a long time ago. I forget the
exact answer, but I vaguely remember it being around an issue with my data,
not with the library. Everyone who's getting this issue should double check
that your source data is correct / makes sense.

**Comment by mastrobardo** [comment]
+1

**Comment by pa7** [comment]
Could you isolate an example where you get this error so I can have a look at it? host it on jsbin / plnkr / codepen / your site, post a link,  and I will have a look at it

**Comment by mastrobardo** [comment]
I'll try later on, sadly the project is a company project and i can't link it here!

Thx

**Comment by roydondsouza** [comment]
Davide,

Create a similar example like Patrick suggested where we could check the
issue.

This way we could debug the code and see what's wrong.

**Comment by dakbias** [comment]
Has anybody has a solution for this problem. It happens sometime here too. Thanks

**Comment by pa7** [comment]
Again, I'd probably be able to help you if you could create an example where this problem occurs and send me a link to have a look at it.

**Comment by pa7** [comment]
I will introduce a few boundary checks to prevent the `canvas`s from getting to this state. please reopen and add a URL to test if this is still present
