### ISSUE TITLE
Errors when using multiple heatmaps on leaflet

### ISSUE THREAD

**Issue by vanderlee** [pa7/heatmap.js#148]
There seems to be an issue in the leaflet plugin that causes erros when trying to use more than one HeatmapOverlay. 

Below is the trace I get from chrome:

    Uncaught TypeError: undefined is not a function leaflet.js:6
        o.Map.o.Class.extend._layerAdd leaflet.js:6
        o.Map.o.Class.extend.eachLayer leaflet.js:6
        o.Map.o.Class.extend._resetView leaflet.js:6
        o.Map.include.setView leaflet.js:9
        o.Map.o.Class.extend.fitBounds leaflet.js:6
        window.onload

Problem seems to be with `this` refering to a singular instance of the `HeatmapOverlay` object. I haven't been able to find a quick fix yet. Will try to add a JSFiddle to demonstrate the issue.

**Comment by tapiamcclung** [comment]
I tried your fix but I am not able to put two overlays. Are there any pointers you could share?

It seems, as mentioned, that if I use the same config variable, there are problems. I was able to add two layers but the first layer that was created and added doesn't show up, I can only see the second one. Upon exploring the html elements, I can see that there are two canvas tags but one of them has height and width attributes equal to 0 and wasn't able to change that.

Any help is appreciated

**Comment by merkylove** [comment]
I faced a problem trying to plot multiple heatmaps: only first heatmapoverlay passed to layers parameter is displayed.

This is the problematic part of code:
```javascript
var heatmapLayer1 = new HeatmapOverlay(cfg1);
var heatmapLayer2 = new HeatmapOverlay(cfg2);
var map = new L.Map('map', {
    center: new L.LatLng(22.0, 114.0),
    zoom: 11,
    layers: [baseLayer, heatmapLayer1, heatmapLayer2]
});
heatmapLayer1.setData(testData1);
heatmapLayer2.setData(testData2);
```

I don't know exactly if it is my mistake or something's wrong under the hood so I will be very happy to hear any ideas.

Thanks for attention.
