### ISSUE TITLE
Aggregation

### ISSUE THREAD

**Issue by mithun35h** [pa7/heatmap.js#152]
Please anyone, share the solution to the below problem

I have 2 geo points x,y their values are 10 and 20 respectively. So when i zoom out x and y combine and form z with the value 30, is this assumption correct? If so, this is total of values of points, how can i get the average?

**Comment by pa7** [comment]
heatmap.js will not aggregate the data for you, heatmap.js will only visualize the data you feed it. So your assumption is incorrect. If the datapoints overlap they behave like the typical "multiply" effect in photoshop, so it will be averaged visually
