### ISSUE TITLE
how to store headmap canvas as a image

### ISSUE THREAD

**Issue by gnanasekaranl** [pa7/heatmap.js#154]
how to store headmap canvas as a image in server side
You say like below but i can't,

heatmapInstance.getDataURL(); // data:image/png;base64...
// ready for saving locally or on the server

**Comment by pa7** [comment]
you could send it to your server via an XMLHttpRequest

**Comment by roydon-tj** [comment]
@gnanasekaranl follow this link. http://www.re-cycledair.com/html-5-canvas-saving-to-a-file-with-php
If you have any doubts let us know.

**Comment by roydondsouza** [comment]
@gnanasekaranl follow this link. http://www.re-cycledair.com/html-5-canvas-saving-to-a-file-with-php
If you have any doubts let us know.
