### ISSUE TITLE
heatmap coordinates for resizable windows

### ISSUE THREAD

**Issue by scarrick68** [pa7/heatmap.js#159]
I am overlaying the points generated by the heatmap onto another image. The points don't line up properly when the window is resized because the png image moves to stay centered. How can I set the x,y values of the data to be compatible with resizable pages?

**Comment by pa7** [comment]
For the static case you could export the heatmap with `heatmapInstance.getDataURL()` and either create a new - resizable - image from the dataURL, or set it as a a background of a resizable div.
