### ISSUE TITLE
Setting empty data crashes Safari on iOS and Chrome on Android

### ISSUE THREAD

**Issue by hpihkala** [pa7/heatmap.js#160]
Hi,

If the first setData() call for a heatmap contains an empty data array, Safari on iOS as well as Chrome on Android crash (exit the process). This may be a bug in said browsers or in heatmap.js.

This is annoying in cases where the data is dynamically loaded and cannot be guaranteed to be non-empty.

Here's a jsfiddle that executes fine (not supposed to show anything, just sets empty data) on desktop Chrome but crashes on the mobile browsers I had available for testing:

http://jsfiddle.net/pa15arfv/2/ 

If you first set non-empty data, and then set the heatmap to empty data to clear it, no crash occurs.

**Comment by vanderlee** [comment]
Have you tried applying pull request 138 or 147? Both of these deal with empty setData.

**Comment by pa7** [comment]
Fixed and will be part of the next tagged version. Thank you for reporting
