### ISSUE TITLE
configure only seems to affect minOpacity and maxOpacity, blur and radius not affected

### ISSUE THREAD

**Issue by bhilleli** [pa7/heatmap.js#165]
I'm trying to reconfigure entire heatmap's 'settings' after initialization, i.e. to reduce or increase radius 'across entire heatmap' (i.e. not even for individual points, but 'across the entire heatmap', as was possible in v1). 

i.e. using this example from the documentation:

var nuConfig = {
  radius: 10,
  maxOpacity: .5,
  minOpacity: 0,
  blur: .75
};
heatmapInstance.configure(nuConfig);

Doesn't seem to work. MaxOpacity and minOpacity changes are reflected; blur and radius are not.

**Comment by bhilleli** [comment]
I figured - v1 didn't have individual point based radi ('radiuses'?), v2 does, so that might have somethign to do with it... Seems correct.

I ran this from the dev console after insantiating a heatmap w/ radius of 40:
```javascript
//set individual radi points to different radius
arr=heatmap._store._radi;
arr.forEach(function(element,x){
    console.log(element); 
    element.forEach(function(coord,y){
       arr[x][y]=15;
    });
});
heatmap.repaint();
```

Lo and behold - radius changed - so I'm guessing something like this has to be added to 'configure'... Not sure about blur yet but TBC... Please let me know if I'm on right track...

BTW: Just out of curiousity, why separate array of radi and another for data (which are push()'d together when you getData())? i.e. why not just array of points {x, y, radius, value}?

**Comment by bhilleli** [comment]
Anyone care to confirm this? It just surprises me that I'm the first to report this!

**Comment by vlamic** [comment]
I have the same issue :(

**Comment by pa7** [comment]
@bhilleli to answer your question: it performs better and makes the rendering easier. The blur configuration property is not supported in v1. I'd recommend using v2, it's faster and more configurable :) If you need help to migrate I wrote a doc about it: https://github.com/pa7/heatmap.js/blob/master/docs/how-to-migrate.md

**Comment by aliosv** [comment]
How to update "blur" if it caches by "radius"?
https://github.com/pa7/heatmap.js/blob/master/build/heatmap.js#L438

**Comment by pa7** [comment]
@aliosv good catch, it should cache by radius and blur

**Comment by aliosv** [comment]
@pa7 #229

**Comment by DrPDash** [comment]
> 
> 
> How to update "blur" if it caches by "radius"?
> https://github.com/pa7/heatmap.js/blob/master/build/heatmap.js#L438
> i.e. heatmap.configure({ blur : value }) doing nothing, until you change radius.

Hi @aliosv, was this ever resolved? I'm still facing this issue after ~4 years! Just started using heatmap+LL recently. No matter what I reset, the blur won't update unless the radius is changed!
