### ISSUE TITLE
What is the good way to quantify the radius

### ISSUE THREAD

**Issue by seifer08ms** [pa7/heatmap.js#168]
Is there any algorithm is find the best suitable radius for data ?

**Comment by mmontes11** [comment]
It would be very nice to have a dynamic radius proportional to the amount of data provided

**Comment by pa7** [comment]
well you could find a formula that introduces that, set a radius for all the datapoints and feed it into heatmap.js.  I'm not a fan of adding it to the library because it introduces additional complexity

**Comment by mmontes11** [comment]
Yep, we can do it by out own.

By the way, I'm very proud of yourlibrary and I used in several profesional and personal projects
