### ISSUE TITLE
max height limit

### ISSUE THREAD

**Issue by maixiaohai** [pa7/heatmap.js#170]
Do heamap.js limit the height? cause when the height exceed 32767,the map can't show. How could I figure it out?

**Comment by pa7** [comment]
Hi there,
unfortunately heatmap.js **currently** follows the [canvas size restrictions](http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element). 

However I plan to change the renderer to a tile-based approach which will solve this problem and there won't be any size restrictions anymore
