### ISSUE TITLE
Slight Lag

### ISSUE THREAD

**Issue by srirams6** [pa7/heatmap.js#171]
I'm querying an API every 3 seconds and drawing the heatmap based on the data. I'm using `setData` to redraw the map. There seems to be a lag when trying to render the heatmap.

Am I doing something wrong here or is this a performance issue?

**Comment by roydondsouza** [comment]
Try to extend the interval to 10 seconds. Do you still see a lag in
rendering?

When you say there is a lag, do you mean your screen freezes or is it just
that the time it takes to render the new changes are more than 4 to 5
seconds?

**Comment by srirams6** [comment]
I meant that it took 3 seconds to render the new changes. But it turns out that there was a really silly error in my code. I'm going to blame that on coding on a Monday morning. :hammer:
