### ISSUE TITLE
Maybe a silly question but how do I initialize heatmap purely for storage of data without ANY rendering

### ISSUE THREAD

**Issue by denisbetsi** [pa7/heatmap.js#174]
Can't seem to figure out how to do this without having to modify your library. I'm sure I'm missing some setting that will let me just use it for recording of events and forego the real time rendering on the page.

**Comment by pa7** [comment]
heatmap.js is a data visualization library, it's not designed **just** for storage so I'd recommend not using it to store data. the event recording on the [heatmap.js](http://www.patrick-wied.at/static/heatmapjs/) website is done seperately

**Comment by denisbetsi** [comment]
Got ya, was confusing because of all the Add data points functionality. So if it was just for display only then I guess it's there just for illustration purposes.
