### ISSUE TITLE
cannot see small values

### ISSUE THREAD

**Issue by alek0313** [pa7/heatmap.js#176]
use case:
min value=0.0001
max value=100
point value=0.1

- cannot render values smaller than 0.2

any suggestions?

**Comment by pa7** [comment]
the library is only able to handle integer point values 
=> multiply min, max, and all the point values by 10^4 and it will work

**Comment by alek0313** [comment]
Doesn't work with integer values either. Only the last data point renders in the example below.
```javascript
            var d = [
                { x: 200, y: 150, value: 1900, radius: 50 },
                { x: 400, y: 150, value: 100, radius: 20 },
                { x: 600, y: 150, value: 10, radius: 10 },
                { x: 800, y: 150, value: 2000, radius: 50 }];
            heatmap.setData({
                min: 1,
                max: 1000000,
                data: d
            });
```

**Comment by pa7** [comment]
I'll look into it, did you try setting a fixed opacity? that will ensure you won't lose datapoints due to very low alpha values

**Comment by alek0313** [comment]
thanks. and yes, im using 0.9 for opacity. the global alpha for canvas seems okay to me, not sure

**Comment by kermitxc** [comment]
seeing the same problem with very large range of min,max

**Comment by padcoe** [comment]
I'm facing same problem. Any workaround to resolve it?

**Comment by padcoe** [comment]
I'm facing same problem. Any work around to resolve it?

**Comment by kannanrbk** [comment]
@pa7  I am facing the same problem.

**Comment by pa7** [comment]
Fixed with https://github.com/pa7/heatmap.js/commit/faa6d1b575c2afca3e2e454cc6ac1cd14fa1dcd4 . this will be part of the next tagged version. Thank you for reporting it
