### ISSUE TITLE
Can I use heatmap.js without license

### ISSUE THREAD

**Issue by ashah-kaira** [pa7/heatmap.js#185]
Hi there, 

Can I use heatmap.js without license. 

There is not much written about license policy on the heatmap site. There is option for Free and Support package only. What kind of support it is? Can I use heatmap.js and publish this in any of my site without license?

Please let me know.

**Comment by pa7** [comment]
As long as you **keep the copyright notice in the heatmap.js code (!)** you can use it on your site for free. 

Apologies if the site is not clear about the license terms, I will change that soon!
If you need help with integrating heatmap.js or would like to implement custom functionality for a specific usecase the support package would grant you direct support from me for a month
