### ISSUE TITLE
heat cutsoff when Map window resized

### ISSUE THREAD

**Issue by boysmovie** [pa7/heatmap.js#188]
I am using heatmap.js for plotting heatmaps on leaflet.js. I am able to render it beautifully. However lets say the initial window/div size is 400x400. Then I resize the window and the div becomes 600x600, the heatmap layer is still sized at 400x400 and cuts-off. When you move the map, you can see the chopped 400x400 area of heatmap.

Anyway to resize or reset the size?

**Comment by coolblades** [comment]
This was fixed by https://github.com/pa7/heatmap.js/pull/126 but the code is not in the master or develop; not sure why. I merged into the base and it works. But I have problem where if your map setting is that user can wrap around the world, then the heapmap is "stuck" in the "page.

**Comment by pa7** [comment]
Fixed with https://github.com/pa7/heatmap.js/commit/1c47578cedca5a3037ebcdc2777fab005101ec0b will be in the next tagged version

**Comment by krzysztofantczak** [comment]
This issue still exists.
