### ISSUE TITLE
Heatmap rendering 

### ISSUE THREAD

**Issue by radutoev** [pa7/heatmap.js#190]
Hello,

I've just started using heatmap, so I can't say that I'm familiar with it.
My use case is that I want to create a heatmap for points within a circle. 

So I added the circle as svg, added a div with points for values that I have and div with the actual heatmap. All html containers are stacked on top of each other and have the same size. 

The coloring of value points follows this logic: 
```javascript
    if(elem.value <= .5){
		fill = '#686b30';
	} else if(elem.value > .5 && elem.value <= .8){
		fill = '#ab9a52';
	} else if(elem.value > .8 && elem.value <= .95){
		fill = '#e38f4f';
	} else if(elem.value > .95){
		fill = '#ba512e'
	}
```

The heatmap is configured like this: 

```javascript
var heatmap = h337.create({
  container: div,
  maxOpacity: .5,
  minOpacity: 0,
  gradient: {
  	'.5': 'blue',
    '.8': 'red',
    '.95': 'yellow'
  }
});
heatmap.setData({
	max: 1,
  	min: 0,
	data: heatData
});
```
The result:

![capture](https://cloud.githubusercontent.com/assets/380429/10600126/d70db402-7710-11e5-882e-21d6b4f5d318.PNG)

What I don't understand is why is there so much yellow, given that I don't have that many points with high values.

**Comment by pa7** [comment]
Hey @radutoev 
if your max is 1, and your min is 0 it means all your datapoints are the maximum (heatmap.js doesn't support decimal values - if you want to visualize decimal value precision I'd recommend multiplying your values with 10^n to get rid of the comma. Please reopen if that doesn't solve your issue
