### ISSUE TITLE
Require h337 in Leaflet plugin

### ISSUE THREAD

**Issue by buremba** [pa7/heatmap.js#193]
Leaflet plugin uses global `h337` object instead of AMD module. When Heatmap is installed with RequireJS, it won't be in global scope so the Leaflet plugin will throw a ReferenceError.

https://github.com/pa7/heatmap.js/blob/master/plugins/leaflet-heatmap.js#L55

**Comment by pa7** [comment]
Fixed in https://github.com/pa7/heatmap.js/commit/aba079a068dbef7185da2a37649d61bc542c394c could you double check?
