### ISSUE TITLE
Memory error using Firefox and Chrome on Windows

### ISSUE THREAD

**Issue by gotsunami** [pa7/heatmap.js#194]
Hello pa7,

I left a note here:
https://github.com/pa7/heatmap.js/commit/11edfedbe688cafd5e42c695a350e193b8fd81c6

The 'memory error' occurs only on Windows versions of these browsers. I guess this is a kind of invalid memory address that neither the browser nor the OS catch.

I commented
```
        // if (this._heatmap) {
        //   this._heatmap.setData(generatedData);
        // }

```
 in `_update` and it works. I do not get the point of this addition by the way. 

Best regards,
Anthony

**Comment by pa7** [comment]
Hey @gotsunami ,
Thank you for reporting!
What does the memory error say? Also, is it for both, the leaflet and the gmaps plugin?

**Comment by gotsunami** [comment]
Hello pa7,

We did not test the gmap plugin. I cannot tell you right now what the message was, I do not use Windows, the error was reported by a client. I think the browser simply said "Memory error" without being anymore specific.

Sorry I cannot help you any further :(

**Comment by pa7** [comment]
Please reopen if there is more evidence for that problem
