### ISSUE TITLE
Can I use heatmap.js with import.

### ISSUE THREAD

**Issue by bokuweb** [pa7/heatmap.js#200]
Can I use heatmap.js with import on babel.
For example.

```
import heatmap from 'heatmap';
```

**Comment by pa7** [comment]
as heatmap.js is supporting amd/umd/commons/node modules this should be possible according to 
http://www.2ality.com/2015/12/babel-commonjs.html

could you double check that and let me know?

**Comment by pa7** [comment]
Please reopen if it's not working

**Comment by bokuweb** [comment]
thunks.
I use  bellow with "babelify": "6.4.0".

```
import heatmap from 'heatmap.js/build/heatmap';
```

```
      heatmap.create({
        container: document.getElementById('heatMapArea'),
        maxOpacity: .5,
        radius: 30,
        blur: .8
      }).setData({
        max: 5,
        data: mapData
      });
```

But, error occured.
```
Uncaught TypeError: Cannot assign to read only property 'data' of #<ImageData>
```

**Comment by bokuweb** [comment]
It works if the following

```
<script src="node_modules/heatmap.js/heatmap.js"></script>
```

```
      h337.create({
        container: document.getElementById('heatMapArea'),
        maxOpacity: .5,
        radius: 30,
        blur: .8
      }).setData({
        max: 5,
        data: mapData
      });
```


Babel add automatically `use strict`.
This has caused the error ?

**Comment by hgascoigne** [comment]
I'm currently using

```import HeatmapJS from 'heatmap.js/heatmap.js'```

in an ES6/Babel project without any issue.

**Comment by bokuweb** [comment]
thunks 

I'll try it!!

**Comment by pa7** [comment]
@hgascoigne thanks for weighing in. @bokuweb does it work for you?

**Comment by bokuweb** [comment]
@pa7 it work!!! thank you!!

**Comment by zsxgb** [comment]
hi  @hgascoigne  

after import HeatmapJS from 'heatmap.js/heatmap.js'
and how do you use it. like
var heatmap = HeatmapJS.h337.create(config)


this make some trouble

**Comment by hgascoigne** [comment]
@zsxgb You should be able to just use `HeatmapJS.create(config)`

**Comment by zsxgb** [comment]
thank you for your help.

Your method is very easy to use I have applied the heatmap in my application
@hgascoigne
