### ISSUE TITLE
`package.json` specifies incorrect `main` file.

### ISSUE THREAD

**Issue by rhys-vdw** [pa7/heatmap.js#208]
The build file is at `build/heatmap.min.js`, but `package.json` specifies `heatman.min.js`. This breaks when using `npm link` or local include.

I assume this is correct for actual published releases, but it should be possible to specify this github repo as a dependency. Now I need to change the value in my fork/local copy, which is a bit awkward for pushing these changes upstream.

I'd also suggest that you do *not* use a minified version of the code as the main entry point for npm. npm users will typically do that minification themselves via Webpack/Browserify on production only. Errors  from Heatmap would be best viewed with their non-minified stack trace (obviously, ha).

Thanks for the library. Getting a repo to work well with npm releases is a fiddly task.

**Comment by pa7** [comment]
@rhys-vdw thank you for reporting, fixed it :)
