### ISSUE TITLE
Leaflet-Plugin: LatLng does only work with flat data

### ISSUE THREAD

**Issue by vipyoshi** [pa7/heatmap.js#213]
I ran into the problem, that I cant use my data with the plugin. The config object provides a field for "latField" and "lngField", however these are access via `entry[latField]` in the plugin code.

My data looks like the following:
`[{ 
    temp: 30, 
    geoPos: { latitude: 50, longitude: 20 }
}]`
Access the value will not work since `entry['geoPos.latitude']` cannot be resolved.

Would be great, if it would be possible to use this plugin without the need to process the data beforehand.

**Comment by pa7** [comment]
I'm sorry, data processing will be necessary w/ the default leaflet plugin implementation as the data schema heatmap.js won't change. Too much flexibility would confuse people who just started. BUT you could adapt the heatmap-leaflet plugin so it works for your specific data format
