### ISSUE TITLE
creating HeatmapOverlay in angular controller returns undefined

### ISSUE THREAD

**Issue by tnusraddinov** [pa7/heatmap.js#215]
Hi thank you for good library.
When creating HeatmapOverlay in angular controller returns undefined
`map = new google.maps.Map(document.getElementById("map"), myOptions);

                // heatmap layer
                heatmap = new HeatmapOverlay(map,
                    {                     
                        "radius": 20,
                        "maxOpacity": 1,                     
                        //            "scaleRadius": true,                         
                        "useLocalExtrema": true,                       
                        latField: 'lat',                        
                        lngField: 'lng',                      
                        valueField: 'weight'                       
                );
                heatmap.setData({
                    max: 8,
                    data: data
                });`
angular.js:13550 TypeError: Cannot read property 'setData' of undefined
From chrome js console:
> angular.js:13550 TypeError: Cannot read property 'setData' of undefined
    at HeatmapOverlay.update (gmaps-heatmap.js:213)
    at HeatmapOverlay.setData (gmaps-heatmap.js:241)
    at reportController.js:53
    at angular.js:11255
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at Scope.$apply (angular.js:17337)
    at done (angular.js:11572)

heatmap.js and gmaps-heatmap.js are included to html, can you help me?

**Comment by arjun-ajith** [comment]
Hey. Ran into same error right now. Have you solved this error?

**Comment by tnusraddinov** [comment]
I found this in heatmaps demo folder. This solves my problem

`// this is important, because if you set the data set too early, the latlng/pixel projection doesn't work`

`	google.maps.event.addListenerOnce(map, "idle", function(){
		heatmap.setDataSet(testData);
	});`

**Comment by malaguitte** [comment]
I was getting a similar error on a simple page (without Angular), after refreshing the page a couple of times. 
The solution suggested by @tnusraddinov fixed it for me :) Thanks!
I had to use the `setData` method, though.

`google.maps.event.addListenerOnce(map, "idle", function() { 
   heatmap.setData(mydata); 
});`
