### ISSUE TITLE
Uncaught ReferenceError: Google / HeatmapOverlay is not defined

### ISSUE THREAD

**Issue by StefanG96** [pa7/heatmap.js#218]
Hi Guys,

I'm getting the above two errors, the first being within the 'gmaps-heatmap.js' file, and the second being when i create a heatmap overlay instance. 

I've been able to get a map to display, just not the heatmap overlay, which i'm guessing the above two errors are preventing it from doing so.

I've imported the scripts as shown, right at the end of the body, before the closing `<body>` tag.
```
<script async defer src="https://maps.googleapis.com/maps/api/js?key=MY_KEY&callback=initMap"> </script>	
<script type = "text/javascript" src="heatmap.js-develop/build/heatmap.js"></script>
<script type = "text/javascript" src="heatmap.js-develop/plugins/gmaps-heatmap.js"></script>
```

It seems like the heatmap library isn't being imported properly. How would I go about fixing this?

Thanks guys,

**Comment by pa7** [comment]
Hey @StefanG96 ,
currently the plugins need a bit of refactoring: heatmap.js is not loaded properly in the plugins (due to a change to support AMD/UMD/CommonJS) I hope I can fix that the next few days. Sorry about the inconvenience

**Comment by mteichtahl** [comment]
This seems to be caused by 

 69: var h337 = typeof require !== 'undefined' ? require('heatmap.js') : window.h337;

in gmaps-heatmap.js

**Comment by StefanG96** [comment]
the line that is giving me the error in gmaps-heatmap.js is line 27: 

 HeatmapOverlay.prototype = new google.maps.OverlayView();

**Comment by mteichtahl** [comment]
Is there a need to require heat map from within a plugin that can't exist without heatmap.js ?

So. What I'm seeing is a cannot require module heatmap.js because it's looking in the plugin directory rather than one up.

**Comment by pa7** [comment]
@StefanG96 I had a look at your error, this is due to gmaps being loaded asyncronously. The gmaps-heatmap.js plugin needs a gmaps reference to initialize itself. Without `defer async` it works properly. If you really need it to be async you could inject `gmaps-heatmap.js` when gmaps has been loaded, and once gmaps-heatmap.js has been executed initialize your map

**Comment by StefanG96** [comment]
That fixed it, thanks heaps!

**Comment by Louisepower** [comment]
@pa7 Hi Patrick
I encountered an error “h337 is not defined” when I use the heatmap.js . It works well in my  other website before. Could you pls tell me what happened . many thanks!!!!

**Comment by Ants-double** [comment]
i also meet the error .I encountered an error “h337 is not defined” when I use the heatmap.js . It works well in my other website before. Could you pls tell me what happened . many thanks!!!! can you help me

**Comment by junzaivip** [comment]
The same issue for me...can you help me

**Comment by Ants-double** [comment]
I run the jsfile in the electron ,then, i allow the electron can run the jsfile ,it's ok
