### ISSUE TITLE
Multiple clicks to load the data , the IE11 browser will get stuck

### ISSUE THREAD

**Issue by baizn** [pa7/heatmap.js#222]
Only in the win7， Multiple clicks to load the data , the IE11 browser will get stuck。because have many many data，so Thus execution ```_drawAlpha``` function, IE 11 will get stuck.
![image](https://cloud.githubusercontent.com/assets/9443867/18352817/75ee2902-7612-11e6-9ed4-d2f59b0a6f90.png)

**Comment by pa7** [comment]
have your tried what I recommended in  #221  ?
wrapping your setData call in a setTimeout

**Comment by baizn** [comment]
wrapping mysetData call in a setTimeout,it works find, thank you very much !

**Comment by pa7** [comment]
@baizn heatmap.js currently renders syncronously. syncronous rendering blocks the main execution thread (and prevents user interactions) until it's done. setTimeout moves the rendering  to the event queue (which does not block) -> happy interactive page :)

I'm currently working on getting asyncronous rendering into the heatmap.js core so you don't have to care about that anymore, it will be part of the next bigger release.

**Comment by baizn** [comment]
Thank you！ In addition, I think there is a certain relationship between the use of too many closures，do you think？
