### ISSUE TITLE
Heatmap is not working inside of uib-tabset in angularjs

### ISSUE THREAD

**Issue by RenukaMP** [pa7/heatmap.js#224]
`<uib-tabset class="tabbable border">
	<uib-tab ng-repeat="floor in floorPlans" heading="{{floor.floor_name}}" select="heatmap()" >
		<div class="row">
			<div class="col-md-12">
			<img class="img-responsive center-image" ng-src="{{floor.file}}" alt="{{floor.floor_name}}"></img>
			<heat-map data="passed_data"></heat-map>
			</div>
		</div>
	</uib-tab>
</uib-tabset>`

**Comment by pa7** [comment]
I'd appreciate a bit more context :) 
- is there an error in the `console` ? 
- does passed_data actually contain data? (maybe it's a scope issue)
- are you using the official angularjs heatmap plugin that is published in this repository?

**Comment by RenukaMP** [comment]
There is no error in console.
Yes im using official angularjs heatmap plugin get from this repo.

**Comment by RenukaMP** [comment]
@pa7 
And also i need a help to how to add background image as dynamic.

Thanks.

**Comment by pa7** [comment]
does `passed_data` actually pass down data?

**Comment by RenukaMP** [comment]
i didn't get any response for passed_data.
The below response is actually i got it for your reference

<heat-map data="passed_data" class="ng-isolate-scope"><div container="" style="position: relative;"><canvas class="heatmap-canvas" width="0" height="0" style="position: absolute; left: 0px; top: 0px;"></canvas></div></heat-map>

**Comment by RenukaMP** [comment]
<heat-map data="passed_data" class="ng-isolate-scope"><div container="" style="position: relative;"><canvas class="heatmap-canvas" width="0" height="0" style="position: absolute; left: 0px; top: 0px;"></canvas></div></heat-map>

**Comment by RenukaMP** [comment]
`<heat-map data="passed_data" class="ng-isolate-scope"><div container="" style="position: relative;"><canvas class="heatmap-canvas" width="0" height="0" style="position: absolute; left: 0px; top: 0px;"></canvas></div></heat-map>`

**Comment by pa7** [comment]
Have you had a look at the example?
`<heatmap id="heatmap-1" data="heatmapData" config="heatmapConfig" ng-click="updateData()"></heatmap>`

1) it's **\<heatmap>** not **\<heat-map>**
2) if it still doesn't work, set the width and height properties:
`<heatmap data="heatmapData" config="heatmapConfig" width="500" height="300"></heatmap>`
3) if there's no data it will not show a heatmap

**Comment by RenukaMP** [comment]
i just changed the name. otherwise the same code is here.
now i set the width and height properties that is working fine.
thanks a lot :)

**Comment by pa7** [comment]
you're welcome
