### ISSUE TITLE
Can't Dynamically Render HeatMaps

### ISSUE THREAD

**Issue by StefanG96** [pa7/heatmap.js#225]
Hi Guys,

I've created a heat map that sources the data from a flat JSON file, which is working fine.

I have another flat JSON file which contains another data set. In response to a button being pressed I want  a new heat map to be rendered using that data, which will dynamically replace the current heat map. I have attempted to use AJAX to achieve this.

Upon pressing the button, the new heat map is not being rendered, instead the same one is. In the console I get the error: 'Uncaught TypeError: Cannot read property 'setData' of undefined'.

Here is a link to the code: https://ghostbin.com/paste/2k8fj

Some help would be much appreciated.

Thanks.

**Comment by pa7** [comment]
Have you tried initializing the heatmap overlay only once?
Right now you're re-initinializing google maps and the heatmap overlay when the button has been pressed.  try just initializing it once and only use `setData` to pass the new data

**Comment by StefanG96** [comment]
Thanks heaps! Got it working!
