### ISSUE TITLE
heatmap layer is not stick to leaflet baselayer

### ISSUE THREAD

**Issue by moby41** [pa7/heatmap.js#226]
I follow the code guide through, and it appears fine at first place.
But when I drag the map, heatmap layer was floating, the red spot changed its supposed point on leaflet map. It's weird.
Can you guys give me some help on this?

**Comment by pa7** [comment]
Could you upload an example that can reproduce your issue? (on jsfiddle or another platform)
Thanks

**Comment by pa7** [comment]
@moby41 closing this as there was no response, feel free to reopen it with more context / data
