### ISSUE TITLE
IE 11 Heatmap Artifacts

### ISSUE THREAD

**Issue by jocooler** [pa7/heatmap.js#228]
Hello,

I realize that the Esri implementation isn't on your site, so it probably doesn't get official support, but I'm wondering if any one has experienced something similar and point toward a workaround. I've posted this over on [the esri heatmap repo as well.](https://github.com/Esri/heatmap-layer-js/issues/9)

Whenever I drag the map in IE (chrome is fine), I'm getting a lot of artifacts like this:

![image](https://cloud.githubusercontent.com/assets/10778364/19450966/7cc3fc36-9479-11e6-8fba-55683da3eb16.png)

They actually do exist on the heatmap canvas, not just the esri layer. Calling `repaint` doesn't clear them, but calling `configure` does, until the next time the map moves. It seems like the canvas is getting cleared only in the area where new drawing needs to happen. I tried making `_renderer.renderPartial()` make a call to `renderAll` but no luck there either.

This isn't 100% reproducible, but it happens about 95% of the time.

I'm using the 2.0.5 of heatmap.js from this repo with the first lines changed as follows to not clash with Esri/Dojo's `define` implementation:

```
;(function (name, context, factory) {

    window[name] = factory();

})("h337", this, function () {

```

and the connector Esri has - [HeatmapLayer.js here](https://github.com/Esri/heatmap-layer-js/tree/master/src).

Like I said, it's great in Chrome, just something funny in IE.

**Comment by jocooler** [comment]
Here's a better picture of the effect.

![image](https://cloud.githubusercontent.com/assets/10778364/19533740/037072c8-960f-11e6-8698-f6c2534fad0a.png)

**Comment by jocooler** [comment]
I have come up with a workaround for the time being. I'm leaving the issue open over on the Esri repo because it seems to be a bug, but not a bug in heatmap.js.

```
 map.on('load', function () {
    if(/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
      ieFix = map.on("extent-change", function() {
        heatLayer.resizeHeatmap(window.innerWidth, window.innerHeight); 
      });
    }
  });
```

**Comment by pa7** [comment]
@jocooler thanks for leaving that here! It seems that the ERSI heatmap layer repo has been abandoned (?) I didn't even know about it til your ticket, will put a link on the heatmap.js website so people can find it easier

**Comment by jocooler** [comment]
Sorry I didn't get back sooner - I got this message that day github was down for the east coast and couldn't see it.

Esri has now implemented heatmaps internally, so the old plugin might be abandoned. Not sure how similar the new implementation is to yours; all I know is that for my custom application the "new" method didn't work and I had to dig and find the previous, more flexible way of doing things. With the fix above it now works great, so you can close this issue if you want.
