### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sorsimu** [pa7/heatmap.js#231]
Hi, I want to start using heatmap.js for commercial project. 
The project is redistributed and it's not public ( internal network access only or public access but with authorization&authentication). 

As a confirmation: In this case, I can use heatmap.js framework for **free** or I have **to pay** "299$-349$ For Companies & Commercial Products" ?

Cheers!

**Comment by wigvp** [comment]
License is MIT: https://github.com/pa7/heatmap.js/blob/master/LICENSE

> to deal in the Software **without restriction**, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or **sell** copies of the Software

So it should be no problem to use the project commercially... I think.
