### ISSUE TITLE
How could I transform the canvas

### ISSUE THREAD

**Issue by QCmu** [pa7/heatmap.js#234]
update: 
solution: using css:
`#heatmap{ 
-webkit-transform: skew(-45deg);
-moz-transform: skew(-45deg);
-o-transform: skew(-45deg);
-ms-transform: skew(-45deg);
}`

Hi ,
I intend to display a heatmap for multiple floors of a building. Therefore I need to transform the rectangular heatmap to a parallelogram. I thought the following code could help, but it didn't work. Any help would be appreciated! 
`canvas.className = 'heatmap-canvas';

    this._width = canvas.width = shadowCanvas.width = config.width || +(computed.width.replace(/px/,''));
    this._height = canvas.height = shadowCanvas.height = config.height || +(computed.height.replace(/px/,''));

    this.shadowCtx = shadowCanvas.getContext('2d');
    this.ctx = canvas.getContext('2d');
    this.ctx.save();
    this.ctx.rotate( (Math.PI / 180) * 90);`

**Comment by pa7** [comment]
have you tried using css and selecting .heatmap-canvas for a CSS transformation?

**Comment by pa7** [comment]
solution is in the issue content:
```css
#heatmap { 
   transform: skew(-45deg);
}
```
