### ISSUE TITLE
Can I use heatmap in jvectormap

### ISSUE THREAD

**Issue by haormj** [pa7/heatmap.js#237]
Now I want to use heatmap in jvectormap, but the document is not mention

**Comment by pa7** [comment]
@haormj heatmap.js does not support jvectormap and there are no plans to support it so far. However you can write a plugin to support it and use heatmap.js as a layer on top of jvectormap. If you have any questions, don't hesitate to ask

**Comment by pa7** [comment]
Please reopen if this is something you're interested in
