### ISSUE TITLE
Can you describe me the algorithm behind heatmap.js, please?

### ISSUE THREAD

**Issue by andreabazerla** [pa7/heatmap.js#240]
Hi, I want to hack your heatmap.js, through reverse engineering, to recreate a custom version for me but code is too complex to understand without any comments.

Can you describe me the algorithm behind heatmap.js, please?

I need the easier but accurate algorithm in pseudo-code of you library.

Thanks!

**Comment by pa7** [comment]
@andreabazerla I wrote a couple of times about heatmap.js and its architecture on my blog, feel free to check it out:
https://www.patrick-wied.at/blog/?s=heatmap  might be helpful
