### ISSUE TITLE
transparency heatmap

### ISSUE THREAD

**Issue by cedricve** [pa7/heatmap.js#244]
Is it possible to draw the heatmap on top of an image, which was previously drawn on the canvas?
The issue I'm now having is that the canvas is cleared, and so the image.

**Comment by pa7** [comment]
- use a separate canvas (!)
- whenever your data (/heatmap) changes draw image on canvas, then export heatmap w/ instance.toDataURL(), load as image, and also draw it on canvas

Hope that helps, reopen if that's not what you needed or if it's unclear

**Comment by cedricve** [comment]
so the idea is that I layer the two canvas?

**Comment by pa7** [comment]
the idea is to merge two images (your background image, your heatmap exported as dataURL) into one single canvas
