### ISSUE TITLE
GeoJson Data

### ISSUE THREAD

**Issue by augustobg** [pa7/heatmap.js#246]
It is possible to implement this using geojson data?
Instead of using params for lat and lng as lat: 'lat'.. 

Im having some problems on how to implement the heat map with my geojson data..so, a little help would be appreciated.

**Comment by pa7** [comment]
You'd have to transform your geojson into lat/lng objects to make it work with heatmap.js

**Comment by augustobg** [comment]
Oh, ok I will try that, any news will comment or close this issue. Thanks
