### ISSUE TITLE
What is the max point numbers?

### ISSUE THREAD

**Issue by oliverland** [pa7/heatmap.js#25]
Hi

I hope it's ok to post this question here.
I would like to say this project is great!!!
I am using google map and I want to create a heatmap.
I've tried to follow your example - and it's works.
I have about 5400 point to add to the map - I've tried it and it doesn't work.

What is the max number of point you can add?

if I need to add about 50000 point - can i use this project or can you recommend other options?
Thanks

**Comment by matthewchoy88** [comment]
@pa7 Did you ever write that blog post about how to aggregate data?
