### ISSUE TITLE
Heatmap not render at all

### ISSUE THREAD

**Issue by farhanhaseeb** [pa7/heatmap.js#255]
I have a canvas of 1920x37260 px, but when i try to draw heatmap on it, it doesn't render and gives error on  Canvas2dRenderer.prototype._colorize with NS_ERROR_FAILURE while it works perfectly with small resolutions.

Please suggest what to do to run this on big resolutions. Thanks

**Comment by LePew** [comment]
This is a huge canvas! Out of bounds? Out of memory? 
I'm afraid the height of a canvas cannot exceed 32767 px on some platforms. Could you check with a canvas of 1920x32767 px?

**Comment by farhanhaseeb** [comment]
Yes, this range is out of bounds and you are right, it cannot exceed the defined limit. So, if this the case, how can we draw heatmap on such dimensions?

**Comment by pa7** [comment]
@farhanhaseeb split it up in multiple, smaller heatmaps that don't exceed the maximum canvas size:
http://stackoverflow.com/questions/6081483/maximum-size-of-a-canvas-element
