### ISSUE TITLE
Certain datasets do not render

### ISSUE THREAD

**Issue by tcomert** [pa7/heatmap.js#260]
I've got a strange issue where some of my datasets do not display on the heatmap. I initially thought it was related to the size of the dataset, position of the points, or strength of the color change, but the datasets are varied in size and all data points have an x/y value that are within the size of my canvas. When I step through the rendering process in the debugger I can see that when the `_getInternalData()` in Store.js is called, `this._data` has a length of 0, whereas with a normal data set this has a > 0 value.

I managed to resolve the problem by adding the following code to the start of `_getInternalData()` but this seems like a very hacky way of fixing the problem, and I'm wondering if I'm simply doing something wrong?

```javascript
if (this._data.length == 0)
{
    var cnt = 0;
    for (var i in this._data)
    {
        cnt++;
    }
    this._data.length = cnt;
}
```

[JSFiddle showing the issue](https://jsfiddle.net/5jo8h73x/3)

**Comment by iamsolarplexus** [comment]
Thank for this.  I ran into the same issue.  It wouldn't render until there was a coordinate set with round integers (instead of two floats).  Your hack fixes it for me, though.  Much obliged.

**Comment by tasn** [comment]
I've also encountered the same issue, and here too, the solution was to surround my values with Math.round() to make sure they are integers. It drove me mad for a while.
Important to note that with some floaty datasets it would work, just not with all.

**Comment by pa7** [comment]
this is due to the nature of how heatmap.js stores values internally, x & y coordinates currently have to be integers. Do you happen to have a usecase where sub-pixel positioning is critical? 
I will update the docs to make it more clear, thank you for reporting!

**Comment by tasn** [comment]
@pa7, docs are nice, but maybe just force them to be ints from within the lib or at least error about it?
I can't speak for the others, but I don't care about sub-pixel positioning, it's just how I interact with the library. In my use-case, generating hitmaps using pixel values makes no sense, so I have a wrapper layer that translates my values to pixels, and the conversion just happens to be non-integer.

**Comment by iamsolarplexus** [comment]
Interesting and glad to know that floats aren't supported.  I did look for that in the docs, so it'll be a good inclusion in the future.  Thanks for keeping this current for us!
