### ISSUE TITLE
Bug located in heatmap.js/examples/angular-heatmap/index.html

### ISSUE THREAD

**Issue by jihgao** [pa7/heatmap.js#263]
The controller declaration became to 
` .controller('HeatmapCtrl', ['$scope', '$heatma
              value: ((Math.random() * max + min) >> 0),p', function($scope, $heatmap) {`

**Comment by pa7** [comment]
@jihgao this has been fixed in `develop` https://github.com/pa7/heatmap.js/blob/develop/examples/angular-heatmap/index.html
