### ISSUE TITLE
Cannot remove heatmap layer

### ISSUE THREAD

**Issue by karenpommeroy** [pa7/heatmap.js#269]
Hi,

I am using leaflet-heatmap plugin.

Some options are not working through configuration so I figured out I could destroy and recreate heatmap (and layer itself).

Now is there any way make a clean remove?
Simple workflow that works with other leaflet layers does not work here since it leaves heatmap instance.
I tried to delete it manually but no luck so far..

**Comment by jasperfirecai2** [comment]
Using leaflet-heatmap.js the following snippet works just fine:
```js
mymap.removeLayer(myheatmapvar);
```

Your question isn't very specific, so if this is not what you're looking for, could you please specify?
