### ISSUE TITLE
I would like to use heatmap in vue electron. How to do it

### ISSUE THREAD

**Issue by zsxgb** [pa7/heatmap.js#270]
I use import heatmap from 'heatmap.js' and use it in the template
Var heatmap = heatmap.h337.create,
This is not the way it is.

Because it will be given
Uncaught TypeError: Can not read property 'create' of undefined

**Comment by pa7** [comment]
@zsxgb have you tried 
```js
import h337 from 'heatmap.js';

var heatmap = h337.create(//...

**Comment by zsxgb** [comment]
I checked the compiled code and found that it was compiled into
Import h337 from 'heatmap.js';
Var heatmapInstance = h337.create ({
       Container: document.querySelector ('. Heatmap')
});

Var _heatmap = require ('heatmap.js');
Var _heatmap2 = _interopRequireDefault (_heatmap);

Var heatmapInstance = _heatmap2.default.create ({
       Container: document.querySelector ('. Heatmap')
     });

It make
/home/zsx/Stacer/node_modules/heatmap.js/build/heatmap.js:336 Uncaught TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
How is this going

**Comment by zsxgb** [comment]
thank you for your help.


Your method is very easy to use I have applied the heatmap in my application
