### ISSUE TITLE
Possible to use flex-box/divs as data points? 

### ISSUE THREAD

**Issue by bellwood** [pa7/heatmap.js#276]
Say I have a grid of 12x12 divs on my page and they each have data-weight attribute value

Would it be possible to draw a heatmap over this 12x12 grid using the data-weight attribute values and locations on the page?

**Comment by pa7** [comment]
Yes:
- [ ] create a heatmap w/ heatmap.js 
- [ ] get all the div positions and create a data object based on positions and weights
- [ ] listen to element resize events and regenerate the dataset when it's fired
