### ISSUE TITLE
Heatmap.js setData() function not removing the old points

### ISSUE THREAD

**Issue by goldengalaxy** [pa7/heatmap.js#283]
I am using heatmap.js to draw, but since I need to update heatmaps in the same canvas, so i used

`heatmapInstance.setData({data:[]});
`

to clear the heatmap which has points on it. But this does not work in my occasion, the old points on the canvas are still there after setData function above. I also tested

`heatmapInstance.setData({newDatas});
`then it draws thenew points on top of the old ones. I am using chrome and anyone knows how to remove the oldpoints on the canvas? here is the function I use to call when drawing new heatmap.

```
function generateHeatmap(frame){
  var heatmapInstance = h337.create({
  container: document.getElementById("heatmapContainer")
});
    
    heatmapInstance.setData(frame);
}
```
 calling the function:
```
generateHeatmap(frame1);
generateHeatmap(frame2);
```
the canvas now has frame1 and frame2 together on it....:(
regards

**Comment by HeWasntOffByMuch** [comment]
```
var heatmapInstance = h337.create({
  container: document.getElementById("heatmapContainer")
});

function generateHeatmap(frame){
    heatmapInstance.setData(frame);
}
```

You're creating new heatmap instance and a new canvas with generateHeatmap call. To avoid this, keep a reference to the original heatmap object and use **setData** method on it. Keep in mind this will trigger redrawing of the entire canvas, so if variable names imply anything here you'd want to draw each frame with **addData**

**Comment by pa7** [comment]
well said @thealmightyone , @goldengalaxy please comment to reopen, I'll close this for now
