### ISSUE TITLE
Disable shadow

### ISSUE THREAD

**Issue by ehsan-sotoodeh** [pa7/heatmap.js#286]
how to remove black shadow around the heatmap area?

**Comment by pa7** [comment]
can you post a screenshot of what you mean? I don't see a black shadow

**Comment by ehsan-sotoodeh** [comment]
![2018-04-08 13_06_49-my map](https://user-images.githubusercontent.com/26613010/38471391-cb294f6e-3b2d-11e8-891b-6a286a0a30bb.png)
There is a black shadow on the borders of heat map that make it looks like it is above the map and not on the map

**Comment by pa7** [comment]
which of the plugins are you using to create your heatmap? 
The shadow is definitely not added by heatmap.js (or any of the plugins)

**Comment by ehsan-sotoodeh** [comment]
This version: 
https://github.com/pa7/heatmap.js/blob/develop/plugins/leaflet-heatmap/leaflet-heatmap.js

**Comment by ehsan-sotoodeh** [comment]
Sorry does anyone have any clue where to look to make that shadow disappear?

**Comment by jasperfirecai2** [comment]
Maybe part of your defined gradient has a dark and transparent color near the edge?
