### ISSUE TITLE
leaflet-heatmap.js cannot handle dynamic configurations

### ISSUE THREAD

**Issue by jasperfirecai2** [pa7/heatmap.js#290]
## Main issue

The base heatmap.js configure() and repaint methods() don't exist in the leaflet plugin, making it impossible to (for example) dynamically change the radius.

### my heatmap: 
```js
function createheat() {
  Heat = new HeatmapOverlay({
  radius: radius,
  scaleRadius: false,
  useLocalExtrema: false,
  maxOpacity: 0.5,
  minOpacity: 0,
  gradient: {0.10: 'red', 0.25: 'orange', 0.55: 'lime', 0.85: 'green'},
  valueField: 'mag'
  });
return Heat;

}
var heat = createheat().addTo(mymap);

heat.setData(data);
```
#### `radius: radius` refers to an external variable that is changed in this function: 
```js
function increaseradius() {
    radius += 5;
    heat.setData(data); //this doesn't do the job. this is where i 
//need the radius to change and repaint
```

## What I've tried:

- redefining heat as a new heatmap
- removing and re-adding the layer
- the configure() and repaint() methods from Heatmap.js (but those don't exist in the plugin)
- setData() with changed radius (this breaks the heatmap completely)

On a side note: setting ` scaleRadius: false,` to `scaleRadius: true, ` has the heatmap just not show up at all.

**Comment by jasperfirecai2** [comment]
## I seem to found how to do it now.
#### The solution lies in these lines:
https://github.com/pa7/heatmap.js/blob/4e64f5ae5754c84fea363f0fcf24bea4795405ff/plugins/leaflet-heatmap/leaflet-heatmap.js#L174-L176
If the option Radius is **NOT** set and is instead part of the data object as a property, you can dynamically adjust the radius. Since `entry` is just a singular object, `entry.radius` can either be automatically assigned through the options OR in the object itself.
## My working code:
### Defining an object in data:
```js 
Data.push({lat: feature.geometry.coordinates[0], lng: feature.geometry.coordinates[1], mag: feature.properties.mag / 10, radius: feature.properties.mag * radius});
```
### My changeradius function:
```js
function increaseRadius() {
                                radius = radius * 1.1;
                                data = getdata();
                                heat.setData(data);
                            }
```
### Side note:
`scaleRadius: true` still breaks my map.

**Comment by selvex** [comment]
For people looking for an answer on how to dynamically edit the configuration when using the leaflet plugin:

In `leaflet-heatmap.js` you can add the function
```
reconfigure: function(cfg) {
      this.cfg = cfg;
      this._heatmap.configure(cfg);
      this._reset();
    },
```
The config object of course has to follow the format defined in the docs. 
This dynamically updates the heatmap for `radius`, `scaleRadius` and `maxOpacity`. I assume the other settings work fine as well.

Tried a lot of stuff and this one seems solid.

**Comment by shinnobi** [comment]
can you provide me a bit of code, i try add reconfigure in leaflet-heatmap.js and in my js code:
        map.on("zoomend",function(){
            var zoom = map.getZoom()
             var cfg = {
             "radius": zoom
           }
           heatmapLayer.reconfigure(cfg)

but it is not work

**Comment by selvex** [comment]
@shinnobi Sure.

In my work I have an `updateHeatmap` function which gets called everytime the heatmap is updated. So basically if the settings change, I call reconfigure. You can find this here:
https://github.com/selvex/flee-vis/blob/4728063ddd82602538356bc9bdb700658737920b/visualization/public/assets/js/controller/flee-vis-controller.js#L243
```javascript
$scope.updateHeatmap = function() {
    if (heatmapVis.isActive())
    {
      heatmapVis.reconfigure($scope.settings.heatmap);
    }
    if (diffVis.isActive())
    {
      diffVis.reconfigure($scope.settings.heatmap);
    }
  };
```

The `reconfigure` function is registered in `leaftlet-heatmap.js` by just adding it to the list of properties it defines. You can see this here:
https://github.com/selvex/flee-vis/blob/4728063ddd82602538356bc9bdb700658737920b/visualization/public/assets/js/leaflet-heatmap.js#L73
```javascript
reconfigure: function(cfg) {
      this.cfg = cfg;
      this._heatmap.configure(cfg);
      this._reset();
    },
```

Hope that helps.

**Comment by DrPDash** [comment]
Hi @selvex , thanks for your tip above but it is not required to modify / or add to the original heatmap.js code. 

You can still access the update from outside (using private methods, which is also not a good practice but is safer than changing the original code without a version update).

Below is the code that will do the trick:
```
var radius_value = 4 // init
var opacity_value = 0.5 // init
var cfg = {
	radius: radius_value,
	scaleRadius: true,
	opacity: opacity_value,
	useLocalExtrema: false,
	latField: 'lat', // your Y var
	lngField: 'lng', // your X var
	valueField: 'intensity', // your variable
	gradient: {
		0.0: 'blue',
		0.3: 'cyan',
		0.6: 'green',
		0.6: 'yellow',
		0.7: 'violet',
		0.8: 'white',
		0.9: 'pink',
		1.0: 'red'
	}
};

// Leaflet call
myLeafletLayer = new HeatmapOverlay(cfg).addTo(map);
myLeafletLayer.setData({
	min: min_val,
	max: max_val,
	data: myData
});

// updateMyLeafletHeatMap() function to refresh view upon a change in cfg (radius, opacity ...)
// call this function when a configuration parameter changes using checkboxes/sliders etc
function updateMyLeafletHeatMap() {
	cfg.radius = new_radius_value;
	cfg.opacity = new_opacity_value;
		myLeafletLayer._heatmap.configure(mhw_cfg);  // call private method but do not changethe original code
		myLeafletLayer._reset(); // call private method but do not change the proginal code
};
```
Hope this helps others as well.



> 
> 
> @shinnobi Sure.
> 
> In my work I have an `updateHeatmap` function which gets called everytime the heatmap is updated. So basically if the settings change, I call reconfigure. You can find this here:
> https://github.com/selvex/flee-vis/blob/4728063ddd82602538356bc9bdb700658737920b/visualization/public/assets/js/controller/flee-vis-controller.js#L243
> 
> ```js
> $scope.updateHeatmap = function() {
>     if (heatmapVis.isActive())
>     {
>       heatmapVis.reconfigure($scope.settings.heatmap);
>     }
>     if (diffVis.isActive())
>     {
>       diffVis.reconfigure($scope.settings.heatmap);
>     }
>   };
> ```
> 
> The `reconfigure` function is registered in `leaftlet-heatmap.js` by just adding it to the list of properties it defines. You can see this here:
> https://github.com/selvex/flee-vis/blob/4728063ddd82602538356bc9bdb700658737920b/visualization/public/assets/js/leaflet-heatmap.js#L73
> 
> ```js
> reconfigure: function(cfg) {
>       this.cfg = cfg;
>       this._heatmap.configure(cfg);
>       this._reset();
>     },
> ```
> 
> Hope that helps.
