### ISSUE TITLE
Setting scaleradius to true gives HUGE radius

### ISSUE THREAD

**Issue by jasperfirecai2** [pa7/heatmap.js#291]
## Main issue
Using leaflet-heatmap.js setting scaleRadius to false works as intended, but setting it to true has the radius value in my object be measured in roughly hundreds of kilometers. this is a bit excessive?
### Elaboration
To clarify what i mean with that: Say, i have a radius property in the object at a value of 100. I would like it to display 100 metres as a radius. I can do this manually, but as the plugin is right now, this would instead create a radius that covers all of Europe and half of Asia and Africa. (centered around Amsterdam).
I don't think it makes sense to have the default be so high and have the user need to divide the radius by 10'000 or more to get their desired radius.
### Code
Some of my code is in this closed issue: #290 
### Screenshot
This is the size i get when my radius value is '50'
![image](https://user-images.githubusercontent.com/8398131/39809041-f93f30b0-5380-11e8-87d4-11ba6a05ac05.png)

**Comment by jasperfirecai2** [comment]
This is the offender, but I'm still not sure why this creates such huge values
https://github.com/pa7/heatmap.js/blob/4e64f5ae5754c84fea363f0fcf24bea4795405ff/plugins/leaflet-heatmap/leaflet-heatmap.js#L103-L114

**Comment by jasperfirecai2** [comment]
Thispull reqeust is related but doesn't solve the "issue" #273

**Comment by Woracheth** [comment]
I thought the unit is in pixel, not in km.

{radius:1, scaleRadius:true} means
1 pixel radius (2 pixel diameter) at zoom level 1
64 pixel radius (128 pixel diameter) at zoom level 7
2048 pixel radius (4096 pixel diameter) at zoom level 12

**Comment by jasperfirecai2** [comment]
That makes sense, i can't believe i missed that when i wrote this
