### ISSUE TITLE
Relative coordinates depending on screen size

### ISSUE THREAD

**Issue by ghost** [pa7/heatmap.js#326]
hello everyone
Im writting a program to implement an heatmap for analysing a website. I getting coordinates for differents users using different screen size. I am getting coordinates from different screen size for the same clicked element( for example a click coordinate on the same button in 1600 x 800  and on 800 x 400).

When I printed the result using my coordinates the two "same" clikc are not printed at the coordinates.
I have tried to convert this coordinates using the current height and width but it does'nt work.

Does anybody have ideas on how could I transform all my coordinates to a fixed screen size to make an average of all my users clicks?

Thanks

**Comment by stellamarkop** [comment]
Hello! Have you found a solution to this? I'm facing the same issue
