### ISSUE TITLE
the heatmap image has been cut

### ISSUE THREAD

**Issue by feifeipan** [pa7/heatmap.js#59]
hi,

 heatmap is really cool.I am trying to use it in my website.

I just render about 500 points in a div, but the heatmap image has been cut.

![image](https://f.cloud.github.com/assets/2155605/476927/61beaa42-b7cf-11e2-9aec-88fd4ce10900.png)

Here is my config
var config = {
    "radius": 15,
    "element": "heatmapEl",
    "visible": true,
    "opacity": 20,
    "gradient": { 0.45: "rgb(0,0,255)", 0.55: "rgb(0,255,255)", 0.65: "rgb(0,255,0)", 0.95: "yellow", 1.0: "rgb(255,0,0)" }
};

var heatmap = heatmapFactory.create(config);

Do I miss something?

Wait online..........

Thanks.

**Comment by pa7** [comment]
fixed, there's now a config option to set width & height explicitly
