### ISSUE TITLE
VML Support / 

### ISSUE THREAD

**Issue by Danielku15** [pa7/heatmap.js#64]
Currently you are using a canvas layer for rendering the heatmap. For old-browser support (IE 6-8) it would be awesome to have a VML fallback. You might know excanvas (http://code.google.com/p/explorercanvas/). 

It shouldn't be that much work to create an abstraction layer for different drawing engines. As far as I know you are using filled rects and arcs for generating the heatmap. Using such an abstraction layer even an SVG drawing should be possible.

**Comment by pa7** [comment]
As nobody else expressed interest in a VML renderer I will close this issue for now
